services:
  auth-service:
    container_name: auth-service
    environment:
      - PORT=7000
    env_file:
      - ./.env

  mysql:
    image: mysql
    container_name: my-mysql-auth-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - auth-service-sql-data:/var/lib/mysql
    networks:
      - auth-service-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my-phpmyadmin-auth-service
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: mypassword
    networks:
      - auth-service-network

networks:
  auth-service-network:
volumes:
  auth-service-sql-data:
