services:
  auth-service:
    # container_name: auth-service
    build:
      context: .
      target: development
    # env_file:
    #   - ./.env
    image: auth-service:dev
    ports:
      - "7001:7001"
    volumes:
      - .:/app
      - /app/node_modules # prevents node_modules overwrite.
    command: npm run local:watch
